dependencies = ['torch', 'torchvision', 'munch', 'tqdm']

from pretrainedmodels.models.fbresnet import fbresnet152
from pretrainedmodels.models.cafferesnet import cafferesnet101
from pretrainedmodels.models.bninception import bninception
from pretrainedmodels.models.resnext import resnext101_32x4d
from pretrainedmodels.models.resnext import resnext101_64x4d
from pretrainedmodels.models.inceptionv4 import inceptionv4
from pretrainedmodels.models.inceptionresnetv2 import inceptionresnetv2
from pretrainedmodels.models.nasnet import nasnetalarge
from pretrainedmodels.models.nasnet_mobile import nasnetamobile
from pretrainedmodels.models.torchvision_models import alexnet
from pretrainedmodels.models.torchvision_models import densenet121
from pretrainedmodels.models.torchvision_models import densenet169
from pretrainedmodels.models.torchvision_models import densenet201
from pretrainedmodels.models.torchvision_models import densenet161
from pretrainedmodels.models.torchvision_models import resnet18
from pretrainedmodels.models.torchvision_models import resnet34
from pretrainedmodels.models.torchvision_models import resnet50
from pretrainedmodels.models.torchvision_models import resnet101
from pretrainedmodels.models.torchvision_models import resnet152
from pretrainedmodels.models.torchvision_models import inceptionv3
from pretrainedmodels.models.torchvision_models import squeezenet1_0
from pretrainedmodels.models.torchvision_models import squeezenet1_1
from pretrainedmodels.models.torchvision_models import vgg11
from pretrainedmodels.models.torchvision_models import vgg11_bn
from pretrainedmodels.models.torchvision_models import vgg13
from pretrainedmodels.models.torchvision_models import vgg13_bn
from pretrainedmodels.models.torchvision_models import vgg16
from pretrainedmodels.models.torchvision_models import vgg16_bn
from pretrainedmodels.models.torchvision_models import vgg19_bn
from pretrainedmodels.models.torchvision_models import vgg19
from pretrainedmodels.models.dpn import dpn68
from pretrainedmodels.models.dpn import dpn68b
from pretrainedmodels.models.dpn import dpn92
from pretrainedmodels.models.dpn import dpn98
from pretrainedmodels.models.dpn import dpn131
from pretrainedmodels.models.dpn import dpn107
from pretrainedmodels.models.xception import xception
from pretrainedmodels.models.senet import senet154
from pretrainedmodels.models.senet import se_resnet50
from pretrainedmodels.models.senet import se_resnet101
from pretrainedmodels.models.senet import se_resnet152
from pretrainedmodels.models.senet import se_resnext50_32x4d
from pretrainedmodels.models.senet import se_resnext101_32x4d
from pretrainedmodels.models.pnasnet import pnasnet5large
from pretrainedmodels.models.polynet import polynet
